/**
 * @generated by apps/docs/scripts/generate-own-props.ts — DO NOT EDIT.
 * Fuente: packages/knowledge/src/corpus/ownProps.ts (OWN_PROPS_BY_COMPONENT).
 * Regenerar: pnpm generate:docs-own-props
 */
export const OWN_PROPS_BY_COMPONENT: Record<string, readonly string[]> = {
  badge: ['variant'],
  button: ['variant', 'size', 'loading'],
  checkbox: ['invalid'],
  'form-field': ['label', 'htmlFor', 'description', 'error', 'children'],
  input: ['invalid'],
  modal: [
    'open',
    'onClose',
    'title',
    'description',
    'closeOnEscape',
    'closeOnBackdrop',
    'children',
  ],
  select: ['invalid'],
  spinner: ['size', 'label'],
}

export function ownPropsFor(component: string): readonly string[] {
  return OWN_PROPS_BY_COMPONENT[component] ?? []
}
