/**
 * @generated by apps/docs/scripts/generate-tokens-data.ts — DO NOT EDIT.
 * Fuente: packages/tokens/src/tokens (semantic/*.json y contrast.json).
 * Regenerar: pnpm generate:docs-tokens-data
 */

/**
 * Relación semantic → primitive: referencias crudas de los fuentes JSON.
 * Solo contiene lo que el export público de @ods-ai/tokens no expone; los
 * valores se resuelven desde `tokens` (light) y las CSS variables (dark).
 */
export const SEMANTIC_REFS: Readonly<Record<string, string>> = {
  'color.action.danger': 'color.red.600',
  'color.action.danger-active': 'color.red.800',
  'color.action.danger-hover': 'color.red.700',
  'color.action.primary': 'color.blue.600',
  'color.action.primary-active': 'color.blue.800',
  'color.action.primary-hover': 'color.blue.700',
  'color.border.default': 'color.gray.500',
  'color.focus.ring': 'color.blue.500',
  'color.status.danger': 'color.red.700',
  'color.status.info': 'color.blue.700',
  'color.status.success': 'color.green.700',
  'color.status.warning': 'color.amber.700',
  'color.surface.background': 'color.gray.50',
  'color.surface.elevated': 'color.gray.100',
  'color.text.default': 'color.gray.900',
  'color.text.disabled': 'color.gray.500',
  'color.text.muted': 'color.gray.600',
  'color.text.on-action': 'color.white',
}

/**
 * Pares de contraste definidos en contrast.json. Los ratios se computan
 * (dato derivado) con la misma fórmula que packages/tokens/src/validate.ts.
 * La clave de CONTRAST_PAIRS es el id del par (no se repite en el valor).
 */
export interface ContrastPair {
  fg: string
  bg: string
  target: number
}

export const CONTRAST_PAIRS: Readonly<Record<string, ContrastPair>> = {
  'text-default-on-background': {
    fg: 'color.text.default',
    bg: 'color.surface.background',
    target: 4.5,
  },
  'text-default-on-elevated': {
    fg: 'color.text.default',
    bg: 'color.surface.elevated',
    target: 4.5,
  },
  'text-muted-on-background': {
    fg: 'color.text.muted',
    bg: 'color.surface.background',
    target: 4.5,
  },
  'text-muted-on-elevated': { fg: 'color.text.muted', bg: 'color.surface.elevated', target: 4.5 },
  'text-disabled-on-background': {
    fg: 'color.text.disabled',
    bg: 'color.surface.background',
    target: 3,
  },
  'text-on-action-on-primary': {
    fg: 'color.text.on-action',
    bg: 'color.action.primary',
    target: 4.5,
  },
  'text-on-action-on-primary-hover': {
    fg: 'color.text.on-action',
    bg: 'color.action.primary-hover',
    target: 4.5,
  },
  'text-on-action-on-primary-active': {
    fg: 'color.text.on-action',
    bg: 'color.action.primary-active',
    target: 4.5,
  },
  'text-on-action-on-danger': {
    fg: 'color.text.on-action',
    bg: 'color.action.danger',
    target: 4.5,
  },
  'text-on-action-on-danger-hover': {
    fg: 'color.text.on-action',
    bg: 'color.action.danger-hover',
    target: 4.5,
  },
  'text-on-action-on-danger-active': {
    fg: 'color.text.on-action',
    bg: 'color.action.danger-active',
    target: 4.5,
  },
  'action-primary-on-background': {
    fg: 'color.action.primary',
    bg: 'color.surface.background',
    target: 3,
  },
  'action-danger-on-background': {
    fg: 'color.action.danger',
    bg: 'color.surface.background',
    target: 3,
  },
  'focus-ring-on-background': { fg: 'color.focus.ring', bg: 'color.surface.background', target: 3 },
  'border-default-on-background': {
    fg: 'color.border.default',
    bg: 'color.surface.background',
    target: 3,
  },
  'status-success-on-background': {
    fg: 'color.status.success',
    bg: 'color.surface.background',
    target: 4.5,
  },
  'status-warning-on-background': {
    fg: 'color.status.warning',
    bg: 'color.surface.background',
    target: 4.5,
  },
  'status-danger-on-background': {
    fg: 'color.status.danger',
    bg: 'color.surface.background',
    target: 4.5,
  },
  'status-info-on-background': {
    fg: 'color.status.info',
    bg: 'color.surface.background',
    target: 4.5,
  },
  'text-on-action-on-status-success': {
    fg: 'color.text.on-action',
    bg: 'color.status.success',
    target: 4.5,
  },
  'text-on-action-on-status-warning': {
    fg: 'color.text.on-action',
    bg: 'color.status.warning',
    target: 4.5,
  },
  'text-on-action-on-status-danger': {
    fg: 'color.text.on-action',
    bg: 'color.status.danger',
    target: 4.5,
  },
  'text-on-action-on-status-info': {
    fg: 'color.text.on-action',
    bg: 'color.status.info',
    target: 4.5,
  },
}
