import type { ComponentExample } from '../examples'

/** Public metadata of a component prop, generated by react-docgen-typescript. */
export interface ComponentPropMetadata {
  name: string
  required: boolean
  type: string
  defaultValue?: string
  description?: string
}

/**
 * Matured component metadata (SPEC §F3): stable identity, description,
 * canonical examples, tokens and canonical routes — the data contract for
 * the docs app and the future AI retrieval layer.
 */
export interface ComponentMetadata {
  /** Stable identity, e.g. 'ods-ai/button'. Never changes across versions. */
  id: string
  /** Type for retrieval: every DS component is 'component'. */
  kind: 'component'
  /** Display name, e.g. 'Button'. */
  name: string
  /** Slug / canonical route segment, e.g. 'button'. */
  component: string
  /** Prose description for the docs app and the AI retrieval layer. */
  description: string
  props: ComponentPropMetadata[]
  variants: string[]
  sizes?: string[]
  /** Token paths (dot format) used by the component CSS. */
  tokensUsed: string[]
  examples: Array<Pick<ComponentExample, 'id' | 'title' | 'description' | 'code'>>
  tags: string[]
  a11ySummary: string
  /** Cuándo usar el componente — guía de decisión (V1-0, P1-1). */
  whenToUse?: string[]
  /** Cuándo NO usar el componente — anti-patrones (V1-0, P1-1). */
  whenNotToUse?: string[]
  /** Comportamiento relevante no evidente desde la API (foco, ARIA, estados). */
  behavior?: string
  /** Canonical route in the docs app. */
  url: string
  /** Canonical source path in the repository. */
  sourcePath: string
}
