import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { flatten, isRef, loadAll, lookup, type TokenTree } from './loader.js'
import { buildResolver, toCssName } from './resolve.js'

export interface GeneratedFiles {
  css: string
  mjs: string
  dts: string
}

function cssValue(raw: string): string {
  return isRef(raw) ? `var(${toCssName(raw)})` : raw
}

function setPath(tree: TokenTree, path: string, value: string): void {
  const segments = path.split('.')
  let current = tree
  for (const segment of segments.slice(0, -1)) {
    const next = current[segment]
    if (typeof next === 'object' && next !== null) {
      current = next as TokenTree
    } else {
      const created: TokenTree = {}
      current[segment] = created
      current = created
    }
  }
  current[segments.at(-1) ?? ''] = value
}

function typeOfTree(tree: TokenTree): string {
  const parts = Object.entries(tree).map(([key, value]) => {
    const keyStr = /^[a-z][a-z0-9]*$/.test(key) ? key : JSON.stringify(key)
    const valueStr = typeof value === 'string' ? JSON.stringify(value) : typeOfTree(value)
    return `readonly ${keyStr}: ${valueStr}`
  })
  return `{ ${parts.join('; ')} }`
}

export function generateAll(tokensDir?: string): GeneratedFiles {
  const layers = loadAll(tokensDir)
  const resolver = buildResolver(layers)
  const flatPrimitive = flatten(layers.primitive, 'primitive')
  const flatSemantic = flatten(layers.semantic, 'semantic')
  const flatComponent = flatten(layers.component, 'component')
  const darkTheme = layers.themes['dark']

  // ---- CSS ----
  const rootLines: string[] = []
  for (const layer of [flatPrimitive, flatSemantic, flatComponent]) {
    for (const { path } of layer) {
      const raw = resolver.raw(path)
      if (raw !== undefined) rootLines.push(`  ${toCssName(path)}: ${cssValue(raw)};`)
    }
  }
  const darkLines: string[] = []
  if (darkTheme) {
    for (const { path } of flatSemantic) {
      const override = lookup(darkTheme, path)
      if (typeof override === 'string') {
        darkLines.push(`  ${toCssName(path)}: ${cssValue(override)};`)
      }
    }
  }
  const css = [
    '/* Generated by @ods-ai/tokens — do not edit manually. */',
    ':root {',
    ...rootLines,
    '}',
    ...(darkLines.length > 0 ? ['', '[data-theme="dark"] {', ...darkLines, '}'] : []),
    '',
  ].join('\n')

  // ---- TypeScript (resolved to light defaults) ----
  const resolvedTree: TokenTree = {}
  for (const layer of [flatPrimitive, flatSemantic, flatComponent]) {
    for (const { path } of layer) {
      const resolved = resolver.resolve(path)
      if (resolved.ok) setPath(resolvedTree, path, resolved.value)
    }
  }
  const leaves = [...flatPrimitive, ...flatSemantic, ...flatComponent]

  const mjs = [
    '// Generated by @ods-ai/tokens — do not edit manually.',
    `export const tokens = ${JSON.stringify(resolvedTree, null, 2)};`,
    '',
    '// getToken is total for every TokenPath (the generator guarantees that every',
    '// leaf in TokenPath exists) and fails fast on unknown paths — it never',
    '// returns undefined silently.',
    'export function getToken(path) {',
    '  const parts = path.split(".");',
    '  let current = tokens;',
    '  for (const part of parts) {',
    '    if (current === undefined || current === null || typeof current !== "object") {',
    '      throw new Error(`Unknown token path: "${path}"`);',
    '    }',
    '    current = current[part];',
    '  }',
    '  if (typeof current !== "string") {',
    '    throw new Error(`Unknown token path: "${path}"`);',
    '  }',
    '  return current;',
    '}',
    '',
  ].join('\n')

  const dts = [
    '// Generated by @ods-ai/tokens — do not edit manually.',
    `export declare const tokens: ${typeOfTree(resolvedTree)};`,
    '',
    `export declare type TokenPath =\n  | ${leaves.map((leaf) => JSON.stringify(leaf.path)).join('\n  | ')};`,
    '',
    'export declare function getToken<T extends TokenPath>(path: T): string;',
    '',
  ].join('\n')

  return { css, mjs, dts }
}

export function writeGenerated(tokensDir?: string): void {
  const files = generateAll(tokensDir)
  // This module lives in packages/tokens/src, so the package root is one level up.
  const outDir = join(import.meta.dirname, '..', 'dist')
  mkdirSync(outDir, { recursive: true })
  writeFileSync(join(outDir, 'tokens.css'), files.css)
  writeFileSync(join(outDir, 'tokens.mjs'), files.mjs)
  writeFileSync(join(outDir, 'tokens.d.ts'), files.dts)
}
