import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { corpus } from '../index'

/**
 * Integrity test (F5.1): every example in the corpus must be byte-identical to
 * the canonical `*.examples.tsx` source. The corpus is built from the metadata
 * JSON generated by @ods-ai/react, which itself imports the canonical example
 * modules — but this test verifies the chain independently by reading the
 * source files and asserting that each corpus example's `code` appears
 * verbatim there, with no duplication, reconstruction or AI generation.
 */

const REACT_SRC = join(import.meta.dirname, '..', '..', '..', 'react', 'src')

function pascalCase(component: string): string {
  return component
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

describe('example integrity (F5.1)', () => {
  for (const entry of corpus) {
    const fileName = `${pascalCase(entry.component)}.examples.tsx`
    const filePath = join(REACT_SRC, entry.component, fileName)

    it(`${entry.component}: canonical example file exists`, () => {
      expect(existsSync(filePath)).toBe(true)
    })

    it(`${entry.component}: every example code exists verbatim in *.examples.tsx`, () => {
      const source = readFileSync(filePath, 'utf8')
      expect(entry.examples.length).toBeGreaterThan(0)
      for (const example of entry.examples) {
        // The corpus stores the evaluated string (real newlines); the source
        // file stores it escaped inside a JS string literal (literal \n).
        // Normalize to the source representation for an exact comparison.
        const sourceForm = example.code.replace(/\n/g, '\\n')
        expect(source, `${entry.component} example "${example.id}"`).toContain(sourceForm)
        // Its id must be declared in the source (no invented examples).
        expect(source).toContain(`id: '${example.id}'`)
      }
    })

    it(`${entry.component}: example count matches the canonical file`, () => {
      const source = readFileSync(filePath, 'utf8')
      const declaredIds = [...source.matchAll(/id: '([^']+)'/g)].map((match) => match[1])
      const corpusIds = entry.examples.map((example) => example.id)
      // Corpus must be exactly the set of declared canonical ids, no more.
      expect(corpusIds.sort()).toEqual([...new Set(declaredIds)].sort())
    })
  }
})
