/**
 * Generates apps/docs/src/data/tokens-data.generated.ts from the token
 * sources in packages/tokens/src/tokens (semantic/*.json y contrast.json).
 *
 * Mismo patrón C1 que own-props.generated.ts (P0): apps/docs consume un
 * artefacto estático commiteado con los datos que NO forman parte del export
 * público de @ods-ai/tokens (referencias semantic → primitive y pares de
 * contraste). Los valores y rutas de los tokens salen del export público
 * (`tokens` runtime + CSS custom properties). packages/tokens no se modifica.
 *
 * Ejecutar con Node >= 22.18 (type-stripping nativo, sin flags):
 *   node apps/docs/scripts/generate-tokens-data.ts
 *   (alias: pnpm generate:docs-tokens-data)
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const TOKENS_DIR = join(here, '..', '..', '..', 'packages', 'tokens', 'src', 'tokens')
const OUT_FILE = join(here, '..', 'src', 'data', 'tokens-data.generated.ts')

/** printWidth de Prettier (.prettierrc.json). */
const PRINT_WIDTH = 100

type TokenTree = { [key: string]: TokenTree | string }

interface ContrastPairSource {
  id: string
  fg: string
  bg: string
  target: number
}

function flattenRefs(tree: TokenTree, prefix = ''): Record<string, string> {
  const refs: Record<string, string> = {}
  for (const [key, value] of Object.entries(tree)) {
    const path = prefix ? `${prefix}.${key}` : key
    if (typeof value === 'string') refs[path] = value
    else Object.assign(refs, flattenRefs(value, path))
  }
  return refs
}

/** Serializa un string como literal TS entre comillas simples. */
function literal(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`
}

/** Renderiza una entrada de CONTRAST_PAIRS en formato Prettier (inline o expandido). */
function renderContrastPair(id: string, pair: Omit<ContrastPairSource, 'id'>): string {
  const inline = `  ${literal(id)}: { fg: ${literal(pair.fg)}, bg: ${literal(pair.bg)}, target: ${pair.target} },`
  if (inline.length <= PRINT_WIDTH) return inline
  return [
    `  ${literal(id)}: {`,
    `    fg: ${literal(pair.fg)},`,
    `    bg: ${literal(pair.bg)},`,
    `    target: ${pair.target},`,
    '  },',
  ].join('\n')
}

export function generateTokensDataArtifact(): string {
  const semantic: Record<string, string> = {}
  const semanticDir = join(TOKENS_DIR, 'semantic')
  for (const file of readdirSync(semanticDir)
    .filter((f) => f.endsWith('.json'))
    .sort()) {
    const parsed = JSON.parse(readFileSync(join(semanticDir, file), 'utf8')) as TokenTree
    Object.assign(semantic, flattenRefs(parsed))
  }
  const semanticKeys = Object.keys(semantic).sort()

  const contrastFile = JSON.parse(readFileSync(join(TOKENS_DIR, 'contrast.json'), 'utf8')) as {
    pairs: ContrastPairSource[]
  }

  const semanticLines = semanticKeys.map(
    (path) => `  ${literal(path)}: ${literal(semantic[path]!)},`,
  )
  const contrastLines = contrastFile.pairs.map((pair) =>
    renderContrastPair(pair.id, { fg: pair.fg, bg: pair.bg, target: pair.target }),
  )

  return [
    '/**',
    ' * @generated by apps/docs/scripts/generate-tokens-data.ts — DO NOT EDIT.',
    ' * Fuente: packages/tokens/src/tokens (semantic/*.json y contrast.json).',
    ' * Regenerar: pnpm generate:docs-tokens-data',
    ' */',
    '',
    '/**',
    ' * Relación semantic → primitive: referencias crudas de los fuentes JSON.',
    ' * Solo contiene lo que el export público de @ods-ai/tokens no expone; los',
    ' * valores se resuelven desde `tokens` (light) y las CSS variables (dark).',
    ' */',
    'export const SEMANTIC_REFS: Readonly<Record<string, string>> = {',
    ...semanticLines,
    '}',
    '',
    '/**',
    ' * Pares de contraste definidos en contrast.json. Los ratios se computan',
    ' * (dato derivado) con la misma fórmula que packages/tokens/src/validate.ts.',
    ' * La clave de CONTRAST_PAIRS es el id del par (no se repite en el valor).',
    ' */',
    'export interface ContrastPair {',
    '  fg: string',
    '  bg: string',
    '  target: number',
    '}',
    '',
    'export const CONTRAST_PAIRS: Readonly<Record<string, ContrastPair>> = {',
    ...contrastLines,
    '}',
    '',
  ].join('\n')
}

/** Escribe el artefacto (idempotente). Punto de entrada del script. */
export function main(): void {
  writeFileSync(OUT_FILE, generateTokensDataArtifact())
  console.log(`✔ ${OUT_FILE}`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main()
}
