/**
 * Generates apps/docs/src/data/own-props.generated.ts from the single source
 * of truth OWN_PROPS_BY_COMPONENT (packages/knowledge/src/corpus/ownProps.ts).
 *
 * Decisión C1 (P0): apps/docs consume un artefacto estático commiteado; nunca
 * importan @ods-ai/knowledge en runtime. Este script y el test de frescura son
 * los únicos sitios que leen la fuente de knowledge (tooling/test, por ruta
 * relativa — sin dependencia runtime).
 *
 * Ejecutar con Node >= 22.18 (type-stripping nativo, sin flags):
 *   node apps/docs/scripts/generate-own-props.ts
 *   (alias: pnpm generate:docs-own-props)
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { OWN_PROPS_BY_COMPONENT } from '../../../packages/knowledge/src/corpus/ownProps.ts'

const here = dirname(fileURLToPath(import.meta.url))
const OUT_FILE = join(here, '..', 'src', 'data', 'own-props.generated.ts')

/** Serializa un string como literal TS entre comillas simples (seguro para identificadores). */
function literal(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`
}

/** Serialización determinista (formato Prettier) de la whitelist. */
/** printWidth de Prettier (.prettierrc.json). */
const PRINT_WIDTH = 100

/** Renderiza un array de props inline o en varias líneas (formato Prettier). */
function renderProps(keyLiteral: string, props: readonly string[]): string {
  const inline = `  ${keyLiteral}: [${props.map(literal).join(', ')}],`
  if (inline.length <= PRINT_WIDTH) return inline
  const wrapped = props.map((prop) => `    ${literal(prop)},`).join('\n')
  return `  ${keyLiteral}: [\n${wrapped}\n  ],`
}

export function generateOwnPropsArtifact(): string {
  const keys = Object.keys(OWN_PROPS_BY_COMPONENT).sort()
  const body = keys
    .map((key) => {
      const props = OWN_PROPS_BY_COMPONENT[key] ?? []
      // Prettier omite las comillas de las claves que son identificadores válidos.
      const keyLiteral = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : literal(key)
      return renderProps(keyLiteral, props)
    })
    .join('\n')

  return [
    '/**',
    ' * @generated by apps/docs/scripts/generate-own-props.ts — DO NOT EDIT.',
    ' * Fuente: packages/knowledge/src/corpus/ownProps.ts (OWN_PROPS_BY_COMPONENT).',
    ' * Regenerar: pnpm generate:docs-own-props',
    ' */',
    'export const OWN_PROPS_BY_COMPONENT: Record<string, readonly string[]> = {',
    body,
    '}',
    '',
    'export function ownPropsFor(component: string): readonly string[] {',
    '  return OWN_PROPS_BY_COMPONENT[component] ?? []',
    '}',
    '',
  ].join('\n')
}

/** Escribe el artefacto (idempotente). Punto de entrada del script. */
export function main(): void {
  writeFileSync(OUT_FILE, generateOwnPropsArtifact())
  console.log(`✔ ${OUT_FILE}`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main()
}
